let nomeCompleto=prompt("Qual o seu nome completo")
let dataNascimento=Number(prompt("Qual sua data de nascimento?"))
let endereço=prompt("Qual o seu endereço")
let cpf=Number(prompt("Qual o seu CPF?"))
let escolaridade=prompt("Qual a sua escolaridade?")
let chn=prompt("Possui CHN?")
let filhos=Number(prompt("Quantos filhos possui?"))
let cargoAtual=prompt("Qual o seu cargo atual?")
let salario=Number(prompt("Qual o seu salario?"))
let comissao=Number(prompt("Recebe comissão?se sim,informe a porcentagem, caso não, responda com zero?"))
let anoAdmissao=Number(prompt("Informe o ano de Admissao"))
console.log(typeof nomeCompleto)
console.log(typeof dataNascimento)
console.log(typeof endereço)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof chn)
console.log(typeof filhos)
console.log(typeof cargoAtual)
console.log(typeof salario)
console.log(typeof comissao)
console.log(typeof anoAdmissao)
console.log(nomeCompleto)
console.log(dataNascimento)
console.log(endereço)
console.log(cpf)
console.log(escolaridade)
console.log(chn)
console.log(filhos)
console.log(cargoAtual)
console.log(salario)
console.log(comissao)
console.log(anoAdmissao)
